const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION:
eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieU8rRG5hcTFGaU02TGJWL0I2MUNuV1NXcGNKTDdNTUVpT25QeEwrVlRtRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVkxBQVlKTTFKbzgzaW0weE1NNUdhTksrWUE3bG5LRGs5MGJNbjdadEhXUT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIrRjljSFJ0S3RMNjJOZ2VoUVViRnVvblFqbXBjZ25UaVpkTFNUak85NEU0PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJkQUpFQnREcnArZEg3NXpsVDhWNEd4S3ZaRzZOV0lhTVppN29ZZmQxamx3PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkdKMmFReFBiQktUZVc3MWxZV3RPMUh0MmxWdXliV0E0VDdueUdTVXEyRTg9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImFtUVdBVTIyeWJPWTg2Zy80N3FMclRwMnhpek1GZkRua0QyVGRKZHdsRUU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZ04wRlVFaGI4QkVncCt4RjlFU2RRZmx4OEt0eVlCQTk2S0FGU045aDZuRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQS9LQzc4cHl2SXN2c2JXcUFzajNLcmE3RGhCM3lwejExYUIydU9EbmRscz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ijc3S3BxcDQyOGh3M2pjajBQL1p6Q1ZvTjJidE1tc2E0ejFkNVhKZXQ4U3JzTDBwdFRaNXZUcEZoNkdTMlhhV29rL1EwNXBZWFhhcVRFRlVjY2NHMWl3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTAxLCJhZHZTZWNyZXRLZXkiOiJxZFEyRmd1TEpVQklJc3FrUmJPaGxMSktscXpOamZKak5mWDh1VjVEL2trPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1NDExMTUxOTE1NEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJBQUM2MEI2QzFENTBEMDdCMzdENEU4RkFGNEY0RjlFNSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzQ0MDMxODQyfV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJFemhUcWNzQlEtYWFpcHgtNmd5V1F3IiwicGhvbmVJZCI6IjJhMTg1NzhkLWQ5OWYtNGM2Yi1hZWEyLTRiZjdkMzU0NDc4OCIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIxRzhMTW54cXVOc1ZQOHV1VWpTNUZvRmxLZnM9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS0g0MmxOdzdXQjZvNXBxc25XTzdnSm1jNmFRPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IkVITVlNMkUyIiwibWUiOnsiaWQiOiIyNTQxMTE1MTkxNTQ6N0BzLndoYXRzYXBwLm5ldCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTGlOb3Q4SEVOR2d6NzhHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiVDhWeUJFUmtzNUlFczhmZzNwaFFCSWpyZkRRWkFCdFZlVlBqaEZUaVRndz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiS2hGU083dW1yUlFkcTBRTUpLTW5CdUZlejZaL0l6dWt2bEg3MU5EeFc0aE03eFhjMHNvVlRzRlNXRURMYmErMlZ1aWQrV0NPMS84YXhJa2pPZzR0Q1E9PSIsImRldmljZVNpZ25hdHVyZSI6IjJGRkRrdE5CNWNJSm9YUk1DcFdqS3ZmMUtnejNMZGZ2cjN5VUZLWkdaQ1pZN3dSWXNXUDMvTWlvUDBabHhMR1RnMC9mY1NWN3hPWVN4UEtOOVduMmlnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU0MTExNTE5MTU0OjdAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCVS9GY2dSRVpMT1NCTFBINE42WVVBU0k2M3cwR1FBYlZYbFQ0NFJVNGs0TSJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc0NDAzMTgzOCwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFFSk0ifQ==": process.env.SESSION_ID || "",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
